spring:
  datasource:
    username: admin
    password: mysqlPassword
    url: jdbc:mysql://localhost:3306/flab
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 200

  data:
    redis:
      host: localhost
      port: 6379
