package co.kr.ticketing.adminconcert.concert.controller.response;

public enum ConcertErrorResponseCode {
	CREATE_ROUNDS_ERROR,
	CREATE_RUNNING_HOUR_ERROR,
	CREATE_RUNNING_MINUTE_ERROR,
	CREATE_TICKETING_START_TIME_ERROR,
	CREATE_OPEN_TIME_ERROR,
	CREATE_SEATS_ERROR,
	NOT_POSSIBLE_UPDATE_STATE
}
