### create reservation token
POST http://localhost:8082/reservations/tokens
Content-Type: application/json

{
  "concertId": 1,
  "sequenceNumber": 1
}

### get reservation token position
GET http://localhost:8082/reservations/tokens/position?
    token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzZXF1ZW5jZU51bWJlciI6MSwiaWQiOjEsInR5cGUiOiJDT05DRVJUIiwiZXhwIjoxNzMxNjgwNjI0LCJpYXQiOjE3MzE2ODA1NjQsIm9yZGVyaW5nIjo3fQ.EJZzjICXrs3RyWXO_CGAfDBQIcM0ka6tzNZwJLvuEYY
